### ISSUE TITLE
Ask question

### ISSUE THREAD

**Issue by Zhousucheng4811** [fpadula/visualcollisionarm#1]
Hello, after reviewing your project, I would like to ask if TD3VisualAugMixed3. py was used during training. But I didn't see using it in train.py

**Comment by fpadula** [comment]
Hi @Zhousucheng481,
That architecture is used when `architecture_type` is set to `TD3VisualAugMixed3` (as seen [here](https://github.com/fpadula/visualcollisionarm/blob/eff2cc883365a30332b22aaa1a85c3e9d8b99b4b/python_scripts/configs/base_config_visual_aug.yaml#L1))

The code responsible for evaluating the actor and critic networks (thus setting the model on the code) can be found, respectively, [here](https://github.com/fpadula/visualcollisionarm/blob/eff2cc883365a30332b22aaa1a85c3e9d8b99b4b/python_scripts/src/TD3/TD3.py#L112) and [here](https://github.com/fpadula/visualcollisionarm/blob/eff2cc883365a30332b22aaa1a85c3e9d8b99b4b/python_scripts/src/TD3/TD3.py#L121).

I hope this answers your question.
